name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: Different-Strokes-Calgary/website-code
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          ssh-key: ${{ secrets.DSC_SSH }}
          submodules: recursive
      
      - name: Pull & update submodules recursively
        run: |
          git submodule update --recursive --remote --checkout
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules: website" || echo "No changes to commit"
          git push
